apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncthing.fullname" . }}
  labels:
    {{- include "syncthing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "syncthing.selectorLabels" . | nindent 4 }}

{{- range .Values.localServices }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "syncthing.fullname" $) .name | lower | quote | trunc 64 }}
  labels:
    {{- include "syncthing.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .name | lower }}
      protocol: {{ .protocol | upper }}
      name: {{ .name | lower }}
  selector:
    {{- include "syncthing.selectorLabels" $ | nindent 4 }}
{{- end }}
